extends: [[spectral:oas, all]]
rules:
  info-contact: off
  no-$ref-siblings: off
  oas2-unused-definition: off
  operation-default-response: off
  operation-description: error
  oas2-parameter-description: error
