// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openshift/assisted-service/models"
)

// DeleteImageReader is a Reader for the DeleteImage structure.
type DeleteImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteImageNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteImageUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteImageForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteImageNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewDeleteImageMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewDeleteImageConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteImageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeleteImageServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteImageNoContent creates a DeleteImageNoContent with default headers values
func NewDeleteImageNoContent() *DeleteImageNoContent {
	return &DeleteImageNoContent{}
}

/*DeleteImageNoContent handles this case with default header values.

Success.
*/
type DeleteImageNoContent struct {
}

func (o *DeleteImageNoContent) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{cluster_id}/images/{image_id}][%d] deleteImageNoContent ", 204)
}

func (o *DeleteImageNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteImageUnauthorized creates a DeleteImageUnauthorized with default headers values
func NewDeleteImageUnauthorized() *DeleteImageUnauthorized {
	return &DeleteImageUnauthorized{}
}

/*DeleteImageUnauthorized handles this case with default header values.

Unauthorized.
*/
type DeleteImageUnauthorized struct {
	Payload *models.InfraError
}

func (o *DeleteImageUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{cluster_id}/images/{image_id}][%d] deleteImageUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteImageUnauthorized) GetPayload() *models.InfraError {
	return o.Payload
}

func (o *DeleteImageUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfraError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteImageForbidden creates a DeleteImageForbidden with default headers values
func NewDeleteImageForbidden() *DeleteImageForbidden {
	return &DeleteImageForbidden{}
}

/*DeleteImageForbidden handles this case with default header values.

Forbidden.
*/
type DeleteImageForbidden struct {
	Payload *models.InfraError
}

func (o *DeleteImageForbidden) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{cluster_id}/images/{image_id}][%d] deleteImageForbidden  %+v", 403, o.Payload)
}

func (o *DeleteImageForbidden) GetPayload() *models.InfraError {
	return o.Payload
}

func (o *DeleteImageForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfraError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteImageNotFound creates a DeleteImageNotFound with default headers values
func NewDeleteImageNotFound() *DeleteImageNotFound {
	return &DeleteImageNotFound{}
}

/*DeleteImageNotFound handles this case with default header values.

Error.
*/
type DeleteImageNotFound struct {
	Payload *models.Error
}

func (o *DeleteImageNotFound) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{cluster_id}/images/{image_id}][%d] deleteImageNotFound  %+v", 404, o.Payload)
}

func (o *DeleteImageNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteImageNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteImageMethodNotAllowed creates a DeleteImageMethodNotAllowed with default headers values
func NewDeleteImageMethodNotAllowed() *DeleteImageMethodNotAllowed {
	return &DeleteImageMethodNotAllowed{}
}

/*DeleteImageMethodNotAllowed handles this case with default header values.

Method Not Allowed.
*/
type DeleteImageMethodNotAllowed struct {
	Payload *models.Error
}

func (o *DeleteImageMethodNotAllowed) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{cluster_id}/images/{image_id}][%d] deleteImageMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *DeleteImageMethodNotAllowed) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteImageMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteImageConflict creates a DeleteImageConflict with default headers values
func NewDeleteImageConflict() *DeleteImageConflict {
	return &DeleteImageConflict{}
}

/*DeleteImageConflict handles this case with default header values.

Error.
*/
type DeleteImageConflict struct {
	Payload *models.Error
}

func (o *DeleteImageConflict) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{cluster_id}/images/{image_id}][%d] deleteImageConflict  %+v", 409, o.Payload)
}

func (o *DeleteImageConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteImageConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteImageInternalServerError creates a DeleteImageInternalServerError with default headers values
func NewDeleteImageInternalServerError() *DeleteImageInternalServerError {
	return &DeleteImageInternalServerError{}
}

/*DeleteImageInternalServerError handles this case with default header values.

Error.
*/
type DeleteImageInternalServerError struct {
	Payload *models.Error
}

func (o *DeleteImageInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{cluster_id}/images/{image_id}][%d] deleteImageInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteImageInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteImageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteImageServiceUnavailable creates a DeleteImageServiceUnavailable with default headers values
func NewDeleteImageServiceUnavailable() *DeleteImageServiceUnavailable {
	return &DeleteImageServiceUnavailable{}
}

/*DeleteImageServiceUnavailable handles this case with default header values.

Unavailable.
*/
type DeleteImageServiceUnavailable struct {
	Payload *models.Error
}

func (o *DeleteImageServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{cluster_id}/images/{image_id}][%d] deleteImageServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeleteImageServiceUnavailable) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteImageServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
