// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openshift/assisted-service/models"
)

// GetImageOKCode is the HTTP code returned for type GetImageOK
const GetImageOKCode int = 200

/*GetImageOK Success.

swagger:response getImageOK
*/
type GetImageOK struct {

	/*
	  In: Body
	*/
	Payload *models.Image `json:"body,omitempty"`
}

// NewGetImageOK creates GetImageOK with default headers values
func NewGetImageOK() *GetImageOK {

	return &GetImageOK{}
}

// WithPayload adds the payload to the get image o k response
func (o *GetImageOK) WithPayload(payload *models.Image) *GetImageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get image o k response
func (o *GetImageOK) SetPayload(payload *models.Image) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetImageUnauthorizedCode is the HTTP code returned for type GetImageUnauthorized
const GetImageUnauthorizedCode int = 401

/*GetImageUnauthorized Unauthorized.

swagger:response getImageUnauthorized
*/
type GetImageUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewGetImageUnauthorized creates GetImageUnauthorized with default headers values
func NewGetImageUnauthorized() *GetImageUnauthorized {

	return &GetImageUnauthorized{}
}

// WithPayload adds the payload to the get image unauthorized response
func (o *GetImageUnauthorized) WithPayload(payload *models.InfraError) *GetImageUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get image unauthorized response
func (o *GetImageUnauthorized) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImageUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetImageForbiddenCode is the HTTP code returned for type GetImageForbidden
const GetImageForbiddenCode int = 403

/*GetImageForbidden Forbidden.

swagger:response getImageForbidden
*/
type GetImageForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewGetImageForbidden creates GetImageForbidden with default headers values
func NewGetImageForbidden() *GetImageForbidden {

	return &GetImageForbidden{}
}

// WithPayload adds the payload to the get image forbidden response
func (o *GetImageForbidden) WithPayload(payload *models.InfraError) *GetImageForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get image forbidden response
func (o *GetImageForbidden) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImageForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetImageNotFoundCode is the HTTP code returned for type GetImageNotFound
const GetImageNotFoundCode int = 404

/*GetImageNotFound Error.

swagger:response getImageNotFound
*/
type GetImageNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetImageNotFound creates GetImageNotFound with default headers values
func NewGetImageNotFound() *GetImageNotFound {

	return &GetImageNotFound{}
}

// WithPayload adds the payload to the get image not found response
func (o *GetImageNotFound) WithPayload(payload *models.Error) *GetImageNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get image not found response
func (o *GetImageNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetImageInternalServerErrorCode is the HTTP code returned for type GetImageInternalServerError
const GetImageInternalServerErrorCode int = 500

/*GetImageInternalServerError Error.

swagger:response getImageInternalServerError
*/
type GetImageInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetImageInternalServerError creates GetImageInternalServerError with default headers values
func NewGetImageInternalServerError() *GetImageInternalServerError {

	return &GetImageInternalServerError{}
}

// WithPayload adds the payload to the get image internal server error response
func (o *GetImageInternalServerError) WithPayload(payload *models.Error) *GetImageInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get image internal server error response
func (o *GetImageInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImageInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetImageServiceUnavailableCode is the HTTP code returned for type GetImageServiceUnavailable
const GetImageServiceUnavailableCode int = 503

/*GetImageServiceUnavailable Unavailable.

swagger:response getImageServiceUnavailable
*/
type GetImageServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetImageServiceUnavailable creates GetImageServiceUnavailable with default headers values
func NewGetImageServiceUnavailable() *GetImageServiceUnavailable {

	return &GetImageServiceUnavailable{}
}

// WithPayload adds the payload to the get image service unavailable response
func (o *GetImageServiceUnavailable) WithPayload(payload *models.Error) *GetImageServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get image service unavailable response
func (o *GetImageServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImageServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
