// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openshift/assisted-service/models"
)

// ListImagesOKCode is the HTTP code returned for type ListImagesOK
const ListImagesOKCode int = 200

/*ListImagesOK Success.

swagger:response listImagesOK
*/
type ListImagesOK struct {

	/*
	  In: Body
	*/
	Payload models.ImageList `json:"body,omitempty"`
}

// NewListImagesOK creates ListImagesOK with default headers values
func NewListImagesOK() *ListImagesOK {

	return &ListImagesOK{}
}

// WithPayload adds the payload to the list images o k response
func (o *ListImagesOK) WithPayload(payload models.ImageList) *ListImagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list images o k response
func (o *ListImagesOK) SetPayload(payload models.ImageList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListImagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.ImageList{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListImagesUnauthorizedCode is the HTTP code returned for type ListImagesUnauthorized
const ListImagesUnauthorizedCode int = 401

/*ListImagesUnauthorized Unauthorized.

swagger:response listImagesUnauthorized
*/
type ListImagesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewListImagesUnauthorized creates ListImagesUnauthorized with default headers values
func NewListImagesUnauthorized() *ListImagesUnauthorized {

	return &ListImagesUnauthorized{}
}

// WithPayload adds the payload to the list images unauthorized response
func (o *ListImagesUnauthorized) WithPayload(payload *models.InfraError) *ListImagesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list images unauthorized response
func (o *ListImagesUnauthorized) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListImagesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListImagesForbiddenCode is the HTTP code returned for type ListImagesForbidden
const ListImagesForbiddenCode int = 403

/*ListImagesForbidden Forbidden.

swagger:response listImagesForbidden
*/
type ListImagesForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewListImagesForbidden creates ListImagesForbidden with default headers values
func NewListImagesForbidden() *ListImagesForbidden {

	return &ListImagesForbidden{}
}

// WithPayload adds the payload to the list images forbidden response
func (o *ListImagesForbidden) WithPayload(payload *models.InfraError) *ListImagesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list images forbidden response
func (o *ListImagesForbidden) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListImagesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListImagesNotFoundCode is the HTTP code returned for type ListImagesNotFound
const ListImagesNotFoundCode int = 404

/*ListImagesNotFound Error.

swagger:response listImagesNotFound
*/
type ListImagesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListImagesNotFound creates ListImagesNotFound with default headers values
func NewListImagesNotFound() *ListImagesNotFound {

	return &ListImagesNotFound{}
}

// WithPayload adds the payload to the list images not found response
func (o *ListImagesNotFound) WithPayload(payload *models.Error) *ListImagesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list images not found response
func (o *ListImagesNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListImagesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListImagesInternalServerErrorCode is the HTTP code returned for type ListImagesInternalServerError
const ListImagesInternalServerErrorCode int = 500

/*ListImagesInternalServerError Error.

swagger:response listImagesInternalServerError
*/
type ListImagesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListImagesInternalServerError creates ListImagesInternalServerError with default headers values
func NewListImagesInternalServerError() *ListImagesInternalServerError {

	return &ListImagesInternalServerError{}
}

// WithPayload adds the payload to the list images internal server error response
func (o *ListImagesInternalServerError) WithPayload(payload *models.Error) *ListImagesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list images internal server error response
func (o *ListImagesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListImagesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListImagesServiceUnavailableCode is the HTTP code returned for type ListImagesServiceUnavailable
const ListImagesServiceUnavailableCode int = 503

/*ListImagesServiceUnavailable Unavailable.

swagger:response listImagesServiceUnavailable
*/
type ListImagesServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListImagesServiceUnavailable creates ListImagesServiceUnavailable with default headers values
func NewListImagesServiceUnavailable() *ListImagesServiceUnavailable {

	return &ListImagesServiceUnavailable{}
}

// WithPayload adds the payload to the list images service unavailable response
func (o *ListImagesServiceUnavailable) WithPayload(payload *models.Error) *ListImagesServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list images service unavailable response
func (o *ListImagesServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListImagesServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
