// Code generated by go-swagger; DO NOT EDIT.

package assisted_service_iso

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openshift/assisted-service/models"
)

// GetPresignedForAssistedServiceISOOKCode is the HTTP code returned for type GetPresignedForAssistedServiceISOOK
const GetPresignedForAssistedServiceISOOKCode int = 200

/*GetPresignedForAssistedServiceISOOK Success.

swagger:response getPresignedForAssistedServiceISOOK
*/
type GetPresignedForAssistedServiceISOOK struct {

	/*
	  In: Body
	*/
	Payload *models.Presigned `json:"body,omitempty"`
}

// NewGetPresignedForAssistedServiceISOOK creates GetPresignedForAssistedServiceISOOK with default headers values
func NewGetPresignedForAssistedServiceISOOK() *GetPresignedForAssistedServiceISOOK {

	return &GetPresignedForAssistedServiceISOOK{}
}

// WithPayload adds the payload to the get presigned for assisted service i s o o k response
func (o *GetPresignedForAssistedServiceISOOK) WithPayload(payload *models.Presigned) *GetPresignedForAssistedServiceISOOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get presigned for assisted service i s o o k response
func (o *GetPresignedForAssistedServiceISOOK) SetPayload(payload *models.Presigned) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPresignedForAssistedServiceISOOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPresignedForAssistedServiceISOUnauthorizedCode is the HTTP code returned for type GetPresignedForAssistedServiceISOUnauthorized
const GetPresignedForAssistedServiceISOUnauthorizedCode int = 401

/*GetPresignedForAssistedServiceISOUnauthorized Unauthorized.

swagger:response getPresignedForAssistedServiceISOUnauthorized
*/
type GetPresignedForAssistedServiceISOUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewGetPresignedForAssistedServiceISOUnauthorized creates GetPresignedForAssistedServiceISOUnauthorized with default headers values
func NewGetPresignedForAssistedServiceISOUnauthorized() *GetPresignedForAssistedServiceISOUnauthorized {

	return &GetPresignedForAssistedServiceISOUnauthorized{}
}

// WithPayload adds the payload to the get presigned for assisted service i s o unauthorized response
func (o *GetPresignedForAssistedServiceISOUnauthorized) WithPayload(payload *models.InfraError) *GetPresignedForAssistedServiceISOUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get presigned for assisted service i s o unauthorized response
func (o *GetPresignedForAssistedServiceISOUnauthorized) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPresignedForAssistedServiceISOUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPresignedForAssistedServiceISOForbiddenCode is the HTTP code returned for type GetPresignedForAssistedServiceISOForbidden
const GetPresignedForAssistedServiceISOForbiddenCode int = 403

/*GetPresignedForAssistedServiceISOForbidden Forbidden.

swagger:response getPresignedForAssistedServiceISOForbidden
*/
type GetPresignedForAssistedServiceISOForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewGetPresignedForAssistedServiceISOForbidden creates GetPresignedForAssistedServiceISOForbidden with default headers values
func NewGetPresignedForAssistedServiceISOForbidden() *GetPresignedForAssistedServiceISOForbidden {

	return &GetPresignedForAssistedServiceISOForbidden{}
}

// WithPayload adds the payload to the get presigned for assisted service i s o forbidden response
func (o *GetPresignedForAssistedServiceISOForbidden) WithPayload(payload *models.InfraError) *GetPresignedForAssistedServiceISOForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get presigned for assisted service i s o forbidden response
func (o *GetPresignedForAssistedServiceISOForbidden) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPresignedForAssistedServiceISOForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPresignedForAssistedServiceISONotFoundCode is the HTTP code returned for type GetPresignedForAssistedServiceISONotFound
const GetPresignedForAssistedServiceISONotFoundCode int = 404

/*GetPresignedForAssistedServiceISONotFound Error.

swagger:response getPresignedForAssistedServiceISONotFound
*/
type GetPresignedForAssistedServiceISONotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPresignedForAssistedServiceISONotFound creates GetPresignedForAssistedServiceISONotFound with default headers values
func NewGetPresignedForAssistedServiceISONotFound() *GetPresignedForAssistedServiceISONotFound {

	return &GetPresignedForAssistedServiceISONotFound{}
}

// WithPayload adds the payload to the get presigned for assisted service i s o not found response
func (o *GetPresignedForAssistedServiceISONotFound) WithPayload(payload *models.Error) *GetPresignedForAssistedServiceISONotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get presigned for assisted service i s o not found response
func (o *GetPresignedForAssistedServiceISONotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPresignedForAssistedServiceISONotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPresignedForAssistedServiceISOInternalServerErrorCode is the HTTP code returned for type GetPresignedForAssistedServiceISOInternalServerError
const GetPresignedForAssistedServiceISOInternalServerErrorCode int = 500

/*GetPresignedForAssistedServiceISOInternalServerError Error.

swagger:response getPresignedForAssistedServiceISOInternalServerError
*/
type GetPresignedForAssistedServiceISOInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPresignedForAssistedServiceISOInternalServerError creates GetPresignedForAssistedServiceISOInternalServerError with default headers values
func NewGetPresignedForAssistedServiceISOInternalServerError() *GetPresignedForAssistedServiceISOInternalServerError {

	return &GetPresignedForAssistedServiceISOInternalServerError{}
}

// WithPayload adds the payload to the get presigned for assisted service i s o internal server error response
func (o *GetPresignedForAssistedServiceISOInternalServerError) WithPayload(payload *models.Error) *GetPresignedForAssistedServiceISOInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get presigned for assisted service i s o internal server error response
func (o *GetPresignedForAssistedServiceISOInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPresignedForAssistedServiceISOInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPresignedForAssistedServiceISOServiceUnavailableCode is the HTTP code returned for type GetPresignedForAssistedServiceISOServiceUnavailable
const GetPresignedForAssistedServiceISOServiceUnavailableCode int = 503

/*GetPresignedForAssistedServiceISOServiceUnavailable Unavailable.

swagger:response getPresignedForAssistedServiceISOServiceUnavailable
*/
type GetPresignedForAssistedServiceISOServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPresignedForAssistedServiceISOServiceUnavailable creates GetPresignedForAssistedServiceISOServiceUnavailable with default headers values
func NewGetPresignedForAssistedServiceISOServiceUnavailable() *GetPresignedForAssistedServiceISOServiceUnavailable {

	return &GetPresignedForAssistedServiceISOServiceUnavailable{}
}

// WithPayload adds the payload to the get presigned for assisted service i s o service unavailable response
func (o *GetPresignedForAssistedServiceISOServiceUnavailable) WithPayload(payload *models.Error) *GetPresignedForAssistedServiceISOServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get presigned for assisted service i s o service unavailable response
func (o *GetPresignedForAssistedServiceISOServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPresignedForAssistedServiceISOServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
