// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openshift/assisted-service/models"
)

// DownloadPXEArtifactReader is a Reader for the DownloadPXEArtifact structure.
type DownloadPXEArtifactReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *DownloadPXEArtifactReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDownloadPXEArtifactOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 307:
		result := NewDownloadPXEArtifactTemporaryRedirect()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDownloadPXEArtifactUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDownloadPXEArtifactForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDownloadPXEArtifactInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDownloadPXEArtifactServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDownloadPXEArtifactOK creates a DownloadPXEArtifactOK with default headers values
func NewDownloadPXEArtifactOK(writer io.Writer) *DownloadPXEArtifactOK {
	return &DownloadPXEArtifactOK{
		Payload: writer,
	}
}

/*DownloadPXEArtifactOK handles this case with default header values.

Success.
*/
type DownloadPXEArtifactOK struct {
	Payload io.Writer
}

func (o *DownloadPXEArtifactOK) Error() string {
	return fmt.Sprintf("[GET /pxe-artifacts][%d] downloadPXEArtifactOK  %+v", 200, o.Payload)
}

func (o *DownloadPXEArtifactOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *DownloadPXEArtifactOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDownloadPXEArtifactTemporaryRedirect creates a DownloadPXEArtifactTemporaryRedirect with default headers values
func NewDownloadPXEArtifactTemporaryRedirect() *DownloadPXEArtifactTemporaryRedirect {
	return &DownloadPXEArtifactTemporaryRedirect{}
}

/*DownloadPXEArtifactTemporaryRedirect handles this case with default header values.

Redirect.
*/
type DownloadPXEArtifactTemporaryRedirect struct {
	Location string
}

func (o *DownloadPXEArtifactTemporaryRedirect) Error() string {
	return fmt.Sprintf("[GET /pxe-artifacts][%d] downloadPXEArtifactTemporaryRedirect ", 307)
}

func (o *DownloadPXEArtifactTemporaryRedirect) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Location
	o.Location = response.GetHeader("Location")

	return nil
}

// NewDownloadPXEArtifactUnauthorized creates a DownloadPXEArtifactUnauthorized with default headers values
func NewDownloadPXEArtifactUnauthorized() *DownloadPXEArtifactUnauthorized {
	return &DownloadPXEArtifactUnauthorized{}
}

/*DownloadPXEArtifactUnauthorized handles this case with default header values.

Unauthorized.
*/
type DownloadPXEArtifactUnauthorized struct {
	Payload *models.InfraError
}

func (o *DownloadPXEArtifactUnauthorized) Error() string {
	return fmt.Sprintf("[GET /pxe-artifacts][%d] downloadPXEArtifactUnauthorized  %+v", 401, o.Payload)
}

func (o *DownloadPXEArtifactUnauthorized) GetPayload() *models.InfraError {
	return o.Payload
}

func (o *DownloadPXEArtifactUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfraError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDownloadPXEArtifactForbidden creates a DownloadPXEArtifactForbidden with default headers values
func NewDownloadPXEArtifactForbidden() *DownloadPXEArtifactForbidden {
	return &DownloadPXEArtifactForbidden{}
}

/*DownloadPXEArtifactForbidden handles this case with default header values.

Forbidden.
*/
type DownloadPXEArtifactForbidden struct {
	Payload *models.InfraError
}

func (o *DownloadPXEArtifactForbidden) Error() string {
	return fmt.Sprintf("[GET /pxe-artifacts][%d] downloadPXEArtifactForbidden  %+v", 403, o.Payload)
}

func (o *DownloadPXEArtifactForbidden) GetPayload() *models.InfraError {
	return o.Payload
}

func (o *DownloadPXEArtifactForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfraError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDownloadPXEArtifactInternalServerError creates a DownloadPXEArtifactInternalServerError with default headers values
func NewDownloadPXEArtifactInternalServerError() *DownloadPXEArtifactInternalServerError {
	return &DownloadPXEArtifactInternalServerError{}
}

/*DownloadPXEArtifactInternalServerError handles this case with default header values.

Error.
*/
type DownloadPXEArtifactInternalServerError struct {
	Payload *models.Error
}

func (o *DownloadPXEArtifactInternalServerError) Error() string {
	return fmt.Sprintf("[GET /pxe-artifacts][%d] downloadPXEArtifactInternalServerError  %+v", 500, o.Payload)
}

func (o *DownloadPXEArtifactInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DownloadPXEArtifactInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDownloadPXEArtifactServiceUnavailable creates a DownloadPXEArtifactServiceUnavailable with default headers values
func NewDownloadPXEArtifactServiceUnavailable() *DownloadPXEArtifactServiceUnavailable {
	return &DownloadPXEArtifactServiceUnavailable{}
}

/*DownloadPXEArtifactServiceUnavailable handles this case with default header values.

Unavailable.
*/
type DownloadPXEArtifactServiceUnavailable struct {
	Payload *models.Error
}

func (o *DownloadPXEArtifactServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /pxe-artifacts][%d] downloadPXEArtifactServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DownloadPXEArtifactServiceUnavailable) GetPayload() *models.Error {
	return o.Payload
}

func (o *DownloadPXEArtifactServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
