// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDownloadPXEArtifactParams creates a new DownloadPXEArtifactParams object
// with the default values initialized.
func NewDownloadPXEArtifactParams() *DownloadPXEArtifactParams {
	var ()
	return &DownloadPXEArtifactParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDownloadPXEArtifactParamsWithTimeout creates a new DownloadPXEArtifactParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDownloadPXEArtifactParamsWithTimeout(timeout time.Duration) *DownloadPXEArtifactParams {
	var ()
	return &DownloadPXEArtifactParams{

		timeout: timeout,
	}
}

// NewDownloadPXEArtifactParamsWithContext creates a new DownloadPXEArtifactParams object
// with the default values initialized, and the ability to set a context for a request
func NewDownloadPXEArtifactParamsWithContext(ctx context.Context) *DownloadPXEArtifactParams {
	var ()
	return &DownloadPXEArtifactParams{

		Context: ctx,
	}
}

// NewDownloadPXEArtifactParamsWithHTTPClient creates a new DownloadPXEArtifactParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDownloadPXEArtifactParamsWithHTTPClient(client *http.Client) *DownloadPXEArtifactParams {
	var ()
	return &DownloadPXEArtifactParams{
		HTTPClient: client,
	}
}

/*DownloadPXEArtifactParams contains all the parameters to send to the API endpoint
for the download p x e artifact operation typically these are written to a http.Request
*/
type DownloadPXEArtifactParams struct {

	/*FileType*/
	FileType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the download p x e artifact params
func (o *DownloadPXEArtifactParams) WithTimeout(timeout time.Duration) *DownloadPXEArtifactParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the download p x e artifact params
func (o *DownloadPXEArtifactParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the download p x e artifact params
func (o *DownloadPXEArtifactParams) WithContext(ctx context.Context) *DownloadPXEArtifactParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the download p x e artifact params
func (o *DownloadPXEArtifactParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the download p x e artifact params
func (o *DownloadPXEArtifactParams) WithHTTPClient(client *http.Client) *DownloadPXEArtifactParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the download p x e artifact params
func (o *DownloadPXEArtifactParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileType adds the fileType to the download p x e artifact params
func (o *DownloadPXEArtifactParams) WithFileType(fileType string) *DownloadPXEArtifactParams {
	o.SetFileType(fileType)
	return o
}

// SetFileType adds the fileType to the download p x e artifact params
func (o *DownloadPXEArtifactParams) SetFileType(fileType string) {
	o.FileType = fileType
}

// WriteToRequest writes these params to a swagger request
func (o *DownloadPXEArtifactParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param file_type
	qrFileType := o.FileType
	qFileType := qrFileType
	if qFileType != "" {
		if err := r.SetQueryParam("file_type", qFileType); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
